"""Reporting — emit JSON, Markdown, a styled HTML report, and SARIF 2.1.0.

Findings are grouped by severity (critical -> info) so the report reads the way
a pentester triages. SARIF lets findings flow into GitHub code scanning / CI.
"""
from __future__ import annotations

import html
import json
from datetime import datetime, timezone

from wstrike import __author__, __version__
from wstrike.core.console import good
from wstrike.core.context import SEVERITIES, Context

# severity -> (markdown/html colour, SARIF level)
_SEV_COLOR = {
    "critical": "#7b1fa2", "high": "#d32f2f", "medium": "#f57c00",
    "low": "#fbc02d", "info": "#0288d1",
}
_SARIF_LEVEL = {
    "critical": "error", "high": "error", "medium": "warning",
    "low": "note", "info": "note",
}


def write_reports(ctx: Context, diff=None) -> dict:
    paths = {
        "json": ctx.artifact_path("report.json"),
        "md": ctx.artifact_path("report.md"),
        "html": ctx.artifact_path("report.html"),
        "sarif": ctx.artifact_path("report.sarif"),
    }
    paths["json"].write_text(_json_report(ctx, diff))
    paths["md"].write_text(_markdown_report(ctx, diff))
    paths["html"].write_text(_html_report(ctx, diff))
    paths["sarif"].write_text(_sarif_report(ctx))
    good(f"Reports written: {paths['md']}  |  +html +sarif +json")
    return {k: str(v) for k, v in paths.items()}


def _json_report(ctx: Context, diff=None) -> str:
    report = {
        "tool": "WebStrike",
        "version": __version__,
        "author": __author__,
        "target": ctx.target,
        "started_at": ctx.started_at,
        "finished_at": datetime.now(timezone.utc).isoformat(),
        "summary": _counts(ctx),
        "findings": [f.to_dict() for f in ctx.findings],
    }
    if diff is not None:
        report["diff"] = {
            "first_run": diff.first_run,
            "new": [f.to_dict() for f in diff.new],
            "known": len(diff.known),
            "resolved": [{"title": r.get("title"), "url": r.get("url")} for r in diff.resolved],
        }
    return json.dumps(report, indent=2)


def _markdown_report(ctx: Context, diff=None) -> str:
    counts = _counts(ctx)
    lines = [
        f"# WebStrike Report — `{ctx.target}`",
        "",
        f"*Generated by WebStrike v{__version__} — created by {__author__}*",
        "",
        f"- **Target:** {ctx.target}",
        f"- **Started:** {ctx.started_at}",
        f"- **Total findings:** {len(ctx.findings)}",
        "",
    ]
    if diff is not None and not diff.first_run:
        lines += [
            "## Changes since last scan",
            "",
            f"- 🆕 **New:** {len(diff.new)}",
            f"- ✓ Known: {len(diff.known)}",
            f"- ✅ Resolved: {len(diff.resolved)}",
            "",
        ]
        if diff.new:
            lines.append("### 🆕 New findings")
            lines.append("")
            for f in diff.new:
                lines.append(f"- **[{f.severity.upper()}]** {f.title} — `{f.target}`")
            lines.append("")
    lines += [
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in reversed(SEVERITIES):
        lines.append(f"| {sev.capitalize()} | {counts.get(sev, 0)} |")
    lines += ["", "## Findings", ""]

    for sev in reversed(SEVERITIES):
        bucket = [f for f in ctx.findings if f.severity == sev]
        if not bucket:
            continue
        lines.append(f"### {sev.upper()} ({len(bucket)})")
        lines.append("")
        for f in bucket:
            lines.append(f"- **{f.title}**")
            lines.append(f"  - Target: `{f.target}`")
            lines.append(f"  - Module: `{f.module}`")
            if f.evidence:
                lines.append(f"  - Evidence: {f.evidence}")
            if f.references:
                lines.append(f"  - References: {', '.join(f.references)}")
        lines.append("")
    return "\n".join(lines)


def _counts(ctx: Context) -> dict[str, int]:
    counts = {s: 0 for s in SEVERITIES}
    for f in ctx.findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return counts


def _html_report(ctx: Context, diff=None) -> str:
    counts = _counts(ctx)
    e = html.escape

    def chip(sev: str) -> str:
        return (f'<span class="chip" style="background:{_SEV_COLOR[sev]}">'
                f'{sev.upper()} {counts.get(sev, 0)}</span>')

    rows = []
    for sev in reversed(SEVERITIES):
        for f in (x for x in ctx.findings if x.severity == sev):
            refs = " ".join(f'<a href="{e(r)}">ref</a>' for r in f.references)
            rows.append(
                f'<tr class="sev-{sev}"><td><span class="dot" '
                f'style="background:{_SEV_COLOR[sev]}"></span>{sev.upper()}</td>'
                f"<td>{e(f.title)}</td><td><code>{e(f.target)}</code></td>"
                f"<td>{e(f.module)}</td><td>{e(f.evidence)} {refs}</td></tr>"
            )

    new_banner = ""
    if diff is not None and not diff.first_run:
        new_banner = (f'<p class="new">🆕 {len(diff.new)} new since last scan · '
                      f'{len(diff.known)} known · {len(diff.resolved)} resolved</p>')

    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>WebStrike — {e(ctx.target)}</title><style>
body{{font:14px/1.5 system-ui,sans-serif;margin:2rem;color:#222;background:#fafafa}}
h1{{margin:0}} .sub{{color:#888}} .chip{{color:#fff;padding:2px 8px;border-radius:10px;
margin-right:6px;font-size:12px;font-weight:600}} .new{{font-weight:600}}
table{{border-collapse:collapse;width:100%;margin-top:1rem;background:#fff}}
th,td{{border:1px solid #e0e0e0;padding:6px 10px;text-align:left;vertical-align:top}}
th{{background:#f0f0f0}} code{{background:#f4f4f4;padding:1px 4px;border-radius:3px}}
.dot{{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px}}
</style></head><body>
<h1>WebStrike Report</h1>
<p class="sub">{e(ctx.target)} · {e(ctx.started_at)} · v{__version__} · by {__author__}</p>
<p>{"".join(chip(s) for s in reversed(SEVERITIES))}</p>
{new_banner}
<table><thead><tr><th>Severity</th><th>Finding</th><th>Target</th>
<th>Module</th><th>Evidence</th></tr></thead>
<tbody>{"".join(rows) or '<tr><td colspan=5>No findings.</td></tr>'}</tbody></table>
</body></html>"""


def _sarif_report(ctx: Context) -> str:
    """SARIF 2.1.0 — consumable by GitHub code scanning and other CI tooling."""
    rules: dict[str, dict] = {}
    results = []
    for f in ctx.findings:
        rule_id = f.metadata.get("cwe") or f.module
        if rule_id not in rules:
            rules[rule_id] = {
                "id": rule_id,
                "name": rule_id,
                "shortDescription": {"text": f.module},
                "helpUri": (f.references[0] if f.references else
                            "https://github.com/"),
            }
        results.append({
            "ruleId": rule_id,
            "level": _SARIF_LEVEL.get(f.severity, "note"),
            "message": {"text": f"{f.title} — {f.evidence}".strip(" —")},
            "properties": {"severity": f.severity, "module": f.module},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": f.target or ctx.target}
                }
            }],
        })
    sarif = {
        "version": "2.1.0",
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "runs": [{
            "tool": {"driver": {
                "name": "WebStrike",
                "version": __version__,
                "informationUri": "https://github.com/",
                "rules": list(rules.values()),
            }},
            "results": results,
        }],
    }
    return json.dumps(sarif, indent=2)
